language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t vishal1201/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true vishal1201/frontend npm run test -- --coverage