language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t vishal1201/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true vishal1201/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-203124594319"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY